#!/usr/bin/env bash

SHEBANG="#!/usr/bin/env bash"

create() {
    echo "$SHEBANG" > "$1"
    chmod u+x "$1"
}

if [ $# -lt 1 ]; then

    echo "ERROR: GIVE AN ARGUMENT NAME FOR YOUR SCRIPT"
    exit 0

elif [ $# -gt 1 ]; then

    # For multiple script on once
    for script in "$@"; do
        create "$script"
    done
fi